apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: devsecops-demo
  name: devsecops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devsecops-demo
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'devsecops-demo'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/agent-inject-secret-database: 'secret/devsecops-demo/database' 
        vault.hashicorp.com/agent-inject-template-database: |
              {{- with secret "secret/devsecops-demo/database" -}}
              mysql -u {{ .Data.data.username }} -p {{ .Data.data.password }} -h database:3306 mydb
              {{- end -}}
    spec:
      serviceAccountName: devsecops-demo
      containers:
      - image: oskarq/devsecops-demo
        name: devsecops-demo
        ports:
        - containerPort: 8080
