apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: devsecops-demo
  name: devsecops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devsecops-demo
    spec:
      containers:
      - image: oskarq/devsecops-demo
        name: devsecops-demo
        ports:
        - containerPort: 8080
        resources: {}
