apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: devsecops-demo
  name: devsecops-demo
spec:
  ports:
  - name: "8080"
    nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: devsecops-demo
  type: NodePort
status:
  loadBalancer: {}
